* Scenario
Kermit the Frog MD PhD, once his quality improvement project is approved
wants to have it live in the registry. This way others can search it and
see what he has done despite being green.
* Approver Implementation
** DONE Bridge module
CLOSED: [2016-08-05 Fri 16:32]
- [X] Use requests module to make the requests
- [X] mocking use settings.ini for endpoint
- [X] registry endpoints being built from settings.ini
- [X] models have in_registry property
- [X] Transfer models
** DONE Determine the signals that submit data when appropriate
CLOSED: [2016-08-05 Fri 11:33]
  + [X] Option 1: signals
    * [X] find right hooks
      * post save
    * [X] make sure that all_signals connects the signals on app ready
** DONE Api user
CLOSED: [2016-08-05 Fri 11:45]
- [X] fixtures contains the api user
- [X] constants file has right api username
- [X] pushdata grabs the username from constants to make those changes
** DONE Model natural key
CLOSED: [2016-08-09 Tue 13:33]
Models must contain a natural key in order for the registry database to
look up and add those related objects. [[https://docs.djangoproject.com/en/1.9/topics/serialization/][Search for "natural key".]] 
- [X] person natural key
- [X] project natural key
- [X] tags natural key
- [X] address natural key
** TODO Related object dependencies
Models cannot be added to a remote database if the foreign keys referenced
in related relationships do not correspond to an existing model in the
remote database.

Therefore when transferring models, we have to transfer them without
their relationships. Some time after, we can link them up.

We could serialize and expand recursively if there wasnt the danger 
of circular dependancies. 

I.E. person A owns project Z which has B is a collaborator on project X 
which has person A as a collaborator. 

Expansion will not terminate in the previous case
*** Pass models without relations
- [ ] when serializing, pass model without relations
- [ ] check to see if adjacent models are in the registry
  - [ ] if yes, connect the relations
  - [ ] if no, get those over sometime 
**** option 1: do not pass relationships
- [ ] periodically check and see if we can connect models
- [ ] when we can submit the connections to make
**** option 2: pass the relationship adjacency matrix
- [ ] pass over all the natural key adjacency information
- [ ] have registry fill in the relationships periodically
** TODO Related object deserialization
Since we are serializing with natural_keys we need to define
how to reserialize. This will be needed in the registry as well
* Registry Implementation
** TODO Api endpoints
** TODO Make sure that the Approver has to log in or verify its identity
